### ISSUE TITLE
problems with fsevents dev dependency

### ISSUE THREAD

**Issue by JuanMsanchez** [CGastrell/awe-some-boilerplate#2]
Im having problems with fsevents when i try `npm install` on root directory, i'm trying to run this boilerplate on a ubuntu 14.04 installation, it looks that fsevents is only for an osx setup [](https://www.npmjs.com/package/fsevents). Here the npm output:

```
npm ERR! Linux 3.13.0-106-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/juansan/Arduino/projects/web-client/npm-debug.log
```

**Comment by CGastrell** [comment]
Weird. As npm log states:
Os: Darwin
Arch: any
Os: Linux
Arch: any

Meaning both linux and darwin should be supported.

The issue has been addressed here:
https://github.com/npm/npm/issues/14042

Will make some tests and get back to you

**Comment by CGastrell** [comment]
I accidentally included the dependency while migrating. Fixed
